### ISSUE TITLE
PeoplePerHour ApplicationID and Secret Key

### ISSUE THREAD

**Issue by venkataravitejavilla** [PeoplePerHour/pph-php-client#4]
Hello, in your description you mentioned we need an ApplicationID and SecretKey. But there is not link on PeoplePerHour site which explains how to get those. Can you shed some light on this? Is this something they used to offer but they dont anymore?

**Comment by tomfotherby** [comment]
Yes, I'm afraid you are correct, PPH currently aren't opening their API up to the public so aren't providing keys at this time.
